import { COUNTRY_LABELS } from "./countries";

export const CATEGORIES = [
  { key: "country", label: "Country", type: "exact", valueLabels: COUNTRY_LABELS, weight: 3 },
  { key: "tour", label: "Tour", type: "exact", valueLabels: { atp: "ATP", wta: "WTA" }, weight: 2 },
  { key: "hand", label: "Plays", type: "exact", valueLabels: { R: "Right-Handed", L: "Left-Handed" } },

  { key: "australian_open_titles", label: "Australian Open", type: "gte", threshold: 1, value: "Champion" },
  { key: "roland_garros_titles", label: "Roland Garros", type: "gte", threshold: 1, value: "Champion" },
  { key: "wimbledon_titles", label: "Wimbledon", type: "gte", threshold: 1, value: "Champion" },
  { key: "us_open_titles", label: "US Open", type: "gte", threshold: 1, value: "Champion" },

  { key: "grand_slam_titles", label: "Grand Slam Titles", type: "gte", threshold: 1, value: "1+" },
  { key: "grand_slam_titles_multi", label: "Grand Slam Titles", type: "gte", threshold: 2, field: "grand_slam_titles", value: "2+" },
  { key: "gs_finalist_no_win", label: "Grand Slam", type: "computed", value: "Finalist (Never Won)", test: (p) => p.grand_slam_finals_lost > 0 && p.grand_slam_titles === 0 },
  { key: "gs_finalist", label: "Grand Slam", type: "computed", value: "Reached Final", test: (p) => p.grand_slam_finals_lost > 0 || p.grand_slam_titles > 0 },

  { key: "titles_1", label: "Career Titles", type: "gte", threshold: 1, field: "total_titles", value: "1+" },
  { key: "titles_5", label: "Career Titles", type: "gte", threshold: 5, field: "total_titles", value: "5+" },
  { key: "titles_10", label: "Career Titles", type: "gte", threshold: 10, field: "total_titles", value: "10+" },
  { key: "titles_20", label: "Career Titles", type: "gte", threshold: 20, field: "total_titles", value: "20+" },

  { key: "masters_1000_titles", label: "Masters/WTA 1000", type: "gte", threshold: 1, value: "Champion" },
  { key: "tour_finals_titles", label: "Tour Finals", type: "gte", threshold: 1, value: "Champion" },
  { key: "olympic_medal", label: "Olympics", type: "boolean", value: "Medalist" },

  { key: "hard_court_titles", label: "Hard Court", type: "gte", threshold: 1, value: "Title Winner" },
  { key: "clay_court_titles", label: "Clay Court", type: "gte", threshold: 1, value: "Title Winner" },
  { key: "grass_court_titles", label: "Grass Court", type: "gte", threshold: 1, value: "Title Winner" },
  { key: "hard_5", label: "Hard Court Titles", type: "gte", threshold: 5, field: "hard_court_titles", value: "5+" },
  { key: "clay_5", label: "Clay Court Titles", type: "gte", threshold: 5, field: "clay_court_titles", value: "5+" },
  { key: "titles_on_all_surfaces", label: "All 3 Surfaces", type: "boolean", value: "Title Winner" },

  { key: "rank_1", label: "Career-High Ranking", type: "computed", value: "#1", test: (p) => p.career_high_rank === 1 },
  { key: "rank_top5", label: "Career-High Ranking", type: "computed", value: "Top 5", test: (p) => p.career_high_rank != null && p.career_high_rank <= 5 },
  { key: "rank_top10", label: "Career-High Ranking", type: "computed", value: "Top 10", test: (p) => p.career_high_rank != null && p.career_high_rank <= 10 },
  { key: "year_end_no1_count", label: "Year-End", type: "gte", threshold: 1, value: "#1" },
  { key: "weeks_50", label: "Weeks at #1", type: "computed", value: "50+", test: (p) => p.weeks_at_no1 >= 50 },

  { key: "wins_300", label: "Career Wins", type: "computed", value: "300+", test: (p) => p.career_wins >= 300 },
  { key: "wins_500", label: "Career Wins", type: "computed", value: "500+", test: (p) => p.career_wins >= 500 },

  {
    key: "height_bucket", label: "Height", type: "exact",
    valueLabels: {
      imperial: { under_175: "Under 5'9\"", "175_182": "5'9\"–6'0\"", "183_189": "6'0\"–6'2\"", "190_plus": "6'3\"+" },
      metric: { under_175: "Under 175cm", "175_182": "175–182cm", "183_189": "183–189cm", "190_plus": "190cm+" },
    },
  },

  { key: "active_decade", label: "Active In", type: "decade" },
  { key: "birth_decade", label: "Born In", type: "exact" },
  { key: "won_title_as_teenager", label: "Won Title", type: "boolean", value: "As Teenager" },
  { key: "turned_pro_young", label: "Turned Pro", type: "computed", value: "Before Age 18", test: (p) => p.pro_year && p.birth_year && (p.pro_year - p.birth_year) < 18 },
  { key: "win_pct_65", label: "Career Win %", type: "computed", value: "65%+", test: (p) => p.career_win_pct >= 65 },
];

export const CONFLICT_PAIRS = [
  ["australian_open_titles", "grand_slam_titles"],
  ["roland_garros_titles", "grand_slam_titles"],
  ["wimbledon_titles", "grand_slam_titles"],
  ["us_open_titles", "grand_slam_titles"],
  ["australian_open_titles", "grand_slam_titles_multi"],
  ["roland_garros_titles", "grand_slam_titles_multi"],
  ["wimbledon_titles", "grand_slam_titles_multi"],
  ["us_open_titles", "grand_slam_titles_multi"],
  ["grand_slam_titles", "grand_slam_titles_multi"],
  ["grand_slam_titles", "gs_finalist_no_win"],
  ["grand_slam_titles_multi", "gs_finalist_no_win"],
  ["gs_finalist_no_win", "gs_finalist"],
  ["grand_slam_titles", "gs_finalist"],
  ["grand_slam_titles_multi", "gs_finalist"],
  ["australian_open_titles", "gs_finalist"],
  ["roland_garros_titles", "gs_finalist"],
  ["wimbledon_titles", "gs_finalist"],
  ["us_open_titles", "gs_finalist"],
  ["titles_1", "titles_5"],
  ["titles_1", "titles_10"],
  ["titles_1", "titles_20"],
  ["titles_5", "titles_10"],
  ["titles_5", "titles_20"],
  ["titles_10", "titles_20"],
  ["rank_1", "rank_top5"],
  ["rank_1", "rank_top10"],
  ["rank_top5", "rank_top10"],
  ["rank_1", "year_end_no1_count"],
  ["rank_1", "weeks_50"],
  ["year_end_no1_count", "weeks_50"],
  ["wins_300", "wins_500"],
  ["active_decade", "birth_decade"],
  ["hard_court_titles", "titles_on_all_surfaces"],
  ["clay_court_titles", "titles_on_all_surfaces"],
  ["grass_court_titles", "titles_on_all_surfaces"],
  ["hard_court_titles", "hard_5"],
  ["clay_court_titles", "clay_5"],
  ["hard_5", "titles_on_all_surfaces"],
  ["clay_5", "titles_on_all_surfaces"],
  ["won_title_as_teenager", "turned_pro_young"],
];
